name: CI

on:
    pull_request:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Rust toolchain
              uses: dtolnay/rust-toolchain@stable

            - name: Run cargo tests
              run: |
                  sudo apt-get update
                  sudo apt-get install -y ffmpeg
                  cargo test --locked
